---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app
  namespace: default
  labels:
    app: nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs-app
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: varaprasadrenati/node-app:latest   # Your Docker image
        ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: default
spec:
  type: NodePort          # NodePort is required for Classic ELB
  selector:
    app: nodejs-app
  ports:
    - name: http
      port: 80            # Port exposed by the service
      targetPort: 3000    # Container port
      nodePort: 3000      # Must match ELB health check
